### ISSUE TITLE
[PE-D][Tester A] CLI should be used for viewing person details

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-4/tp#129]
- This flaw is related to the bug report about the lack of documentation on the need to click employees to see their details

The expected use case intends for users to use the CLI to quickly navigate and find employees. When an employee is found and the user wishes to see their details, they must click on the employee to expand their displayed attributes. Clicking a different employee or clicking elsewhere on the app's interface collapses the details shown back to the name, tags and phone number again.

- Refer to the [CS2103/T project constraints](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-constraints.html), specifically `Constraint-Typing-Preferred`
	- A major part of the intended workflow using this app would require users to be able to see details about ther employees.
	- For each individual employee, they would need to perform searches and listing using the keyboard.
	- To see details they need to expand each employee's details by clicking on them one-by-one, defeating the time-saving uses of the CLI.
	- The inability to see more than one person's full details at a time is also a major hassle when managing large numbers of people.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: H4mes/ped#12

**Comment by h4ow3i** [comment]
Cannot do anything about it due to feature freeze
